### ISSUE TITLE
Support for Docker, and other security-related updates

### ISSUE THREAD

**Issue by horcsinbalint** [EotvosCollegium/mars#377]
We are making some security updates on our current deployment. We started using Docker containers, where each component has its own Docker container. We have a container with a reverse proxy handling SSL which forwards all requests coming to Mars to a different container running NGINX which serves the static content and forwards every request requiring dynamic content to a different container running PHP FPM. (These changes could also come with some performance benefits.) During this update, we have also set up a Raspberry PI next to the printer which is directly connected to it via USB. With this, we have found some settings that there were no great way of configuring.

There is a work-in-progress [deployment](https://github.com/EotvosCollegium/mars/tree/deployment) branch which has some half-baked solutions for several issues. I am planning on making these changes in a more conventional way.

Subtasks for this issue:
- [x] #372 : Running a reverse proxy handling SSL needs to be set in Laravel
- [x] #364 : Using Docker allows us to use proper caching
- [x] #366 : Using an external RPI for printing requires support for external CUPS server
- [x] #373 : For some reason, `pdflatex` command does not work in PHP's exec function in Docker
- [x] #378 : We should have a proper workflow on how the code is managed
- [x] #379 : We should have a staging environment where we can test out changes with data from the production server before deploying it to production

Additional subtasks might be added and additional description might be written in the future. The issue description will be updated accordingly.
